# Generated by Django 2.2.3 on 2019-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='facilty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='jaega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('sub_location', models.CharField(max_length=10)),
                ('priority_volunteer', models.CharField(max_length=10)),
            ],
        ),
    ]
