# Generated by Django 2.2.3 on 2019-08-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='anoymous', max_length=20),
            preserve_default=False,
        ),
    ]
