# Generated by Django 2.2.3 on 2019-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_usermodel_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facilty',
            new_name='Facility',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
