# Generated by Django 2.2.3 on 2019-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190829_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('sub_location', models.CharField(max_length=10)),
                ('priority_volunteer', models.CharField(max_length=10)),
            ],
        ),
    ]
