# Generated by Django 2.2.3 on 2019-09-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_loginusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='loginusermodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='loginusermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loginusermodel',
            name='priority_volunteer',
        ),
        migrations.RemoveField(
            model_name='loginusermodel',
            name='sub_location',
        ),
    ]
