# Generated by Django 2.2.3 on 2019-09-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190902_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUserModel',
        ),
    ]
