# Generated by Django 2.2.3 on 2019-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_delete_loginusermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='community',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='jaega',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='other',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='professional',
            name='contents',
            field=models.CharField(max_length=5000),
        ),
    ]
